services: 
  postgres:
    image: postgres:16
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sample
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgres-data:/var/lib/postgresql/data
    networks:
      - sample-network

  migrator:
    build:
      context: .
      dockerfile: Dockerfile-Migrator
    restart: on-failure
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=sample;Username=postgres;Password=postgres"
    depends_on:
      - postgres
    networks:
      - sample-network

  host:
    build:
      context: .
      dockerfile: Dockerfile-Host
    restart: on-failure
    ports:
      - 5000:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=sample;Username=postgres;Password=postgres"
    depends_on:
      - postgres
      - migrator
    networks:
      - sample-network
        
networks:
    sample-network:
        driver: bridge
